-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  mer. 30 jan. 2019 à 09:53
-- Version du serveur :  5.7.23
-- Version de PHP :  7.2.10

SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `gamegear`
--

-- --------------------------------------------------------

--
-- Structure de la table `about`
--

DROP TABLE IF EXISTS `about`;
CREATE TABLE IF NOT EXISTS `about` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ;

--
-- Déchargement des données de la table `about`
--

INSERT INTO `about` (`id`, `description`) VALUES
(1, 'Bienvenue sur le site - En travaux - Projet 5 personnel formation développeur web junior OpenClassrooms');

-- --------------------------------------------------------

--
-- Structure de la table `admin`
--

DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS `admin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ;

--
-- Déchargement des données de la table `admin`
--

INSERT INTO `admin` (`id`, `username`, `password`) VALUES
(1, 'ntonyyy', '5089c85ccf5f86430ff2df9f5fea88eedcaa659d');

-- --------------------------------------------------------

--
-- Structure de la table `chat`
--

DROP TABLE IF EXISTS `chat`;
CREATE TABLE IF NOT EXISTS `chat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(255) NOT NULL,
  `message` text NOT NULL,
  PRIMARY KEY (`id`)
) ;

--
-- Déchargement des données de la table `chat`
--

INSERT INTO `chat` (`id`, `pseudo`, `message`) VALUES
(7, 'Bob', 'Ca va super bien !'),
(1, 'ntonyyy', 'coucou'),
(2, 'ntonyyy', 'Comment allez vous ?'),
(12, 'TOTO', 'hello'),
(53, 'TOTO', 're'),
(52, 'ntonyyy', 'azeaze'),
(51, 'test', 'test');

-- --------------------------------------------------------

--
-- Structure de la table `comments`
--

DROP TABLE IF EXISTS `comments`;
CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `post_id` int(11) NOT NULL,
  `comment` varchar(255) NOT NULL,
  `comment_date` datetime NOT NULL,
  `author` varchar(255) NOT NULL,
  `signaled` tinyint(1) NOT NULL DEFAULT '0',
  `seen` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ;

--
-- Déchargement des données de la table `comments`
--

INSERT INTO `comments` (`id`, `post_id`, `comment`, `comment_date`, `author`, `signaled`, `seen`) VALUES
(5, 13, 'test', '2019-01-22 00:00:00', 'test', 0, 0),
(4, 19, 'test', '2019-01-14 00:00:00', 'test', 1, 0);

-- --------------------------------------------------------

--
-- Structure de la table `datasheet`
--

DROP TABLE IF EXISTS `datasheet`;
CREATE TABLE IF NOT EXISTS `datasheet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `developer` varchar(255) NOT NULL,
  `publisher` varchar(255) NOT NULL,
  `release_date` year(4) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `cover` varchar(255) NOT NULL,
  `screenshot` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL DEFAULT 'ntonyyy',
  `date` timestamp NOT NULL,
  `track` varchar(255) NOT NULL,
  `trackname` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ;

--
-- Déchargement des données de la table `datasheet`
--

INSERT INTO `datasheet` (`id`, `title`, `content`, `developer`, `publisher`, `release_date`, `genre`, `cover`, `screenshot`, `author`, `date`, `track`, `trackname`) VALUES
(1, 'Astérix and the Secret Mission', '<p>Getafix the Druid is out of magic potion! If Caesar finds out, it\'s invasion for sure. Asterix and Obelix set out to find the necessary herbs. A mission through all sorts of Roman-infested terrain - seas and rivers, forests and deserts, temples and ruins.</p>', 'SEGA', 'SEGA', 1993, 'Romans on the Gaul', '43f6493ef01c5a27d2aa20854f5540b51543962907.jpg', '722ee9164649da8317154987752618c01543962907.jpg', 'ntonyyy', '2018-12-04 22:35:07', '5cea0bdf2a4d682bf5d4aa0dc4a089f31543962907.mp3', 'Romans on the Gaul'),
(2, 'Batman Returns', '<p>Leap with Batman into wild acrobatic battle! The Penguin has Gotham City gripped in his twisted flippers. Track the Dark Knight\'s most feared enemies through intense search-and-destroy danger! Attack the deranged Red Triangle Circus Gang with the Caped Crusader\'s own weapons. Swing on grappling hooks across collapsing rooftops. Pitch deadly Batarangs. Rage down goon-infested streets in the Batmobile. Waylay mobs of street thugs by hurling smoke bombs, wrist-shields and swarms of bats from Batman\'s Utility Belt. Dodge Catwoman\'s slashing claws and swinging kick. Duel with the homicidal Juggler. Fight murderous Gargoyles and machinegun-toting clowns. Then slog through poisoned sewers to a heart-stopping face-off in The Penguin\'s lair!</p>', 'Aspect', 'SEGA', 1992, 'action', '6e410c8881cbb9fdfe95cb3a80115c0a1544091547.jpg', '8145a48e4a347553974ce7ebfa2d67a61544091547.jpg', 'ntonyyy', '2018-12-06 10:19:07', '91e73698d2291bc7e5420b99dce2895e1544091547.mp3', 'Stage 1 Gotham City'),
(3, 'Castle of Illusion starring Mickey Mouse', '<p>The search is on! Mickey Tackles magnificent lands where fantasy and danger become real. A waterspout whirls Mickey around. A frantic Toyland suddenly flips upside down. To stay on his feet, Mickey runs, leaps, and bounces, slinging apples and marbles at his enemies. Mickey is on the trail of a wicked Witch named Mizrabel, who has kidnaped Minnie. Mickey must find seven gems hidden in the fantastic chambers and underground mazes of Mizrabel\'s Castle of Illusion and use them to save Minnie. In this scary adventure, Mickey must brave chomping Bonefish, vaporous Ghosts, and taunting Bats. He must battle knights and leaping dragons! Wobble with Mickey on floating leaves, but look out for spiders! Venture into a looney library where even the books attack! Then, get ready to challenfe your most dangerous foe, evil Witch Mizrabel herself!</p>', 'SEGA', 'SEGA', 1991, 'platform', 'b4916e9b65bdcdb91a6a84f9a78fe9541544092132.jpg', '8df33b409c7818d4663869af920399e51544092132.jpg', 'ntonyyy', '2018-12-06 10:28:52', 'ce57c7e67d2d3e74afed2079dd878a3d1544092132.mp3', 'Swimming in the Tea'),
(4, 'Cool Spot', '<p>Charge, blast and hurdle through this fun and frantic adventure without losing your cool - or your shades! As COOL SPOT, you\'ll stop at nothing to rescue your SPOT buddies when they get snatched by powers uncool! Shoot the curl, get loco on a runaway train, and whip through a stomach-dropping rollercoaster ride in a carbonated quest to chill out your foes! Graphics so hot - you\'ll need your own shades!</p>', 'Virgin Games', 'Virgin Games', 1993, 'platform', '7b454338c1c7dd6f973e64d4ba24d09f1544093007.jpg', '02544894cdbd83eec5e8fd1b8570474e1544093007.jpg', 'ntonyyy', '2018-12-06 10:43:27', 'b07962d09004d0ac307365f9fc37e6b21544093007.mp3', 'Rave Dance Tune'),
(5, 'Ecco the Dolphin', 'You are Ecco, a powerful young dolphin. A mysterious storm has swept your family from the sea. The search to find them will take you through vast underwater realms of treachery, beauty and adventure. Use your sonar to discover hidden caverns and unlock the secrets of crystal glyphs. Charge packs of bloodthirsty sharks. Dive deep... but don\'t linger too long, because you\'re a mammal and need air to breathe. In your quest, you\'ll discover that more than your family\'s safety is at stake. The fate of the whole world rests on your wits and fins. Explore giant levels of solving puzzles and fighting denizens of the sea. Knife through the waters, flip above the waves, with motions created from real dolphins.', 'Novotrade', 'SEGA', 1994, 'action-adventure', 'ecco.jpg', 'https://gamefaqs.akamaized.net/screens/0/e/1/gfs_87571_2_4.jpg', 'ntonyyy', '2018-11-25 16:01:53', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/ecco-the-dolphin/11%20-%20Dark%20Water.mp3', 'Dark Water'),
(6, 'The GG Shinobi', 'Shinobi. It\'s Japanese for stealth, the perfect description of a Master Ninja. And that\'s exactly what you are! Armed with throwing stars and finely-honed battle skills, you must defeat the Ring of Five. Fight your way past mercenaries and karate thugs. Take out the meanest martial artists and rescue hostages. But these dangers pale in comparison to your ultimate challenge: A fight to the death against five evil Ninja Assassins whose mastery of the deadly ancient arts may well surpass your own!', 'SEGA', 'SEGA', 1991, 'action', 'ggshinobi.jpg', 'https://gamefaqs.akamaized.net/screens/f/b/3/gfs_2266_1_2.jpg', 'ntonyyy', '2018-11-25 16:01:53', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/shinobi/20%20-%20Ending.mp3', 'Ending'),
(7, 'The Lion King', 'You think you want to be King? Get real. You\'re starting life as Simba, the cub. To survive and grow into a powerful adult lion, you must perfect your savage pounce, reckless roar and master fighting with all four paws. If you survive the challenge, you\'ll grow into a strong, ferocious adult lion. So prepare to scrap with hyenas. Blast through an elephant graveyard. Battle an in-your-face stampede of trampling wildebeests. And you\'d better quit hanging with slackers like Timon and Pumbaa, unless you want to be scarfing bugs the rest of your life! Are you sure you want to be King? Then it\'s time to cut loose in the deadliest one-on-one brawl ever. Defeat your evil Uncle Scar. Recapture the Pridelands. And reclaim your rightful place in the Circle of Life!', 'Syrox Developments', 'SEGA', 1995, 'platform', 'lionking.jpg', 'https://gamefaqs.akamaized.net/screens/3/a/5/gfs_39183_2_1.jpg', 'ntonyyy', '2018-11-25 16:01:53', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/lion-king-the/07.mp3', 'The Stampede - To Die For'),
(8, 'Mappy', 'The player guides Mappy the police mouse through the mansion of the cats called the Meowkies (Mewkies in Japan) to retrieve stolen goods. The player uses a left-right joystick to move Mappy and a single button to operate doors. The mansion has six floors, four or five in some other versions, of hallways in which the stolen items are stashed. Mappy and the cats move between floors by bouncing on trampolines at various places in the house. Both Mappy and the cats can land on a floor on the way up, but not on the way down. When they pass in the air, Mappy is unharmed by the cats, but if Mappy runs into a cat anywhere else, he will lose a life. The trampolines will break if Mappy bounces on them four times in a row. The trampolines change color depending on how many times Mappy has used them without a rest. In addition to the Meowkies, the boss cat Goro (Nyamco in Japanese) also roams around. He is faster, but less aggressive than the Meowkies. Throughout the levels, Goro hides behind the different recoverable objects. If Mappy recovers an item which Goro is hiding behind, the player receives 1000 points.', 'Namcot', 'Namcot', 1991, 'platform', 'mappy.jpg', 'https://gamefaqs.akamaized.net/screens/5/b/b/gfs_8480_2_1_mid.jpg', 'ntonyyy', '2018-11-25 16:01:53', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/mappy/01%20BGM%20%2301.mp3', 'BGM #1'),
(9, 'Pengo', 'Go skating on thin ice! Race Pengo, the lovable penguin, around a frozen lake. Rearrange huge blocks of ice. Your goal: line up three jewel-embedded blocks for dazzling points! Your enemies: SNO-BEES! Their touch puts you in deep freeze.', 'Coreland', 'SEGA', 1991, 'maze', 'pengo.jpg', 'https://gamefaqs.akamaized.net/screens/d/5/9/gfs_89127_2_2_mid.jpg', 'ntonyyy', '2018-11-25 16:01:53', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/pengo/03%20-%20In-Game%20Music.mp3', 'In Game Music'),
(10, 'Sonic the Hedgehog', 'It\'s Super Sonic!!! He\'s here! It\'s Sonic The Hedgehog on Game Gear! And he\'s busting the speed barrier wide open! Blaze by in a blur with his supersonic spin attack. Soar through the tingling rings for super scores. And dash past trouble with Sonic\'s power-sneakers. Smirk in the face of danger as you sail over glistening hills, scuttle over crumbling bridges and hops rocks in a raging waterfall. Swim through underwater passageways. And plummet down tunnels. Are you ready for life in the fast lane? Then get into gear... with Sonic The Hedgehog on Game Gear! Super pace! Super graphics! And Sonic\'s super attitude! Soar through BONUS LEVELS brimming with springs, bumpers, flippers, and more. 5 super challenging zones with 3 acts in each zone.', 'Ancient', 'SEGA', 1991, 'platform', 'sonic.jpg', 'https://gamefaqs.akamaized.net/screens/c/3/3/gfs_39241_2_17_mid.jpg', 'ntonyyy', '2018-11-25 16:01:53', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/sonic-the-hedgehog/04%20Labyrinth%20Zone.mp3', 'Labyrinth Zone'),
(11, 'Wagyan Land', '<p>The series stars Wagyan, a mysterious creature resembling a green mechanical dinosaur who must protect his homeland of Wagyan Land from the mad scientist Dr. Devil. The games features standard side-scrolling stages where the player must reach the goal, as well as boss encounter where the player must compete in a mini-game such as concentration and shiritori.</p>', 'Now Production', 'Namcot', 1991, 'platform', '6785702fa0560fb36c720f8bfae7bfdd1544095471.jpg', 'ee50cc9e1319431caec11e0e6ac90b951544095471.jpg', 'ntonyyy', '2018-12-06 11:24:31', '7410c49294afa062546174a41da9b6611544095471.mp3', 'Land BGM 1'),
(12, 'The GG Shinobi II: The Silent Fury', 'Shinobi, the Ninja Master, returns with his team of expert warriors. Wage a bone-wrenching battle against a pack of evil ninjas who threaten the world. Attack with 5 different ninjas. Each has his own special Ninja Magic.\r\nDecimate opponents with swirling Tornado or awesome Earthquake attacks. Outmaneuver enemies with the incredible new Spider Walk. More power, more moves and more Ninja Magic than ever before.', 'SEGA', 'SEGA', 1992, 'action', 'ggshinobi2.jpg', 'https://gamefaqs.akamaized.net/screens/8/9/3/gfs_39233_2_5.jpg', 'ntonyyy', '2018-11-25 23:00:00', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/shinobi-ii/23%20-%20Extro.mp3', 'Extro'),
(13, 'Ax Battler A Legend of Golden Axe', 'Use your wits and your razor sharp sword to recapture the Golden Axe from the diabolical Death Adder. Defeat skeletons and giant bats in dark, deep chasms and caves. And summon Earth, Thunder and Fire Magic to fight gargoyles that come to life before your eyes!', 'Aspect', 'SEGA', 1991, 'action-adventure', '880610cebd6213d14762792700bed95b1544091292.jpg', '9791029ed1de954ca5c074b09f1880b71544091292.jpg', 'ntonyyy', '2018-12-06 10:14:53', 'cfab1d23eb0192a9355b73792da286161544091292.mp3', 'Ice Cliffs'),
(14, 'Dynamite Headdy ', '<p>Hot-headed Headdy gets into some real head-banging to thwart the Dark Demon\'s devious deeds. This wacky headcase is up to his neck in surprises! Switch heads to match the job! Over 15 heads to choose from! Bash heavy objects with Slammer Head! Suck up foes with Vacuum Head! Stick it to your enemies with Spike Head! Headdy\'s spring-loaded head gets him where he\'s gotta go! Use it to swing over ledges, grab onto objects and shoot hoops in the basketball bonus round. Use your head to whiz through a radical variety of play! Action, shooting and strategy speed you on to a surprise ending!</p>', 'Minato Giken ', 'SEGA ', 1994, 'platform ', 'dynamiteheaddy.jpg', 'https://gamefaqs.akamaized.net/screens/c/5/5/gfs_39152_2_1_mid.jpg', 'ntonyyy', '2019-01-30 08:58:05', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/dynamite-headdy/03%20-%20You%27re%20Izayoi.mp3', 'South Town\'s Theme'),
(15, 'Earthworm Jim', '<p>Jim wasn\'t always a studly super-worm. He was once just a spineless, dirt eater with no real mission in life... Then a cosmic twist of fate placed him in control of an ultra-high-tech-indestructible-super-space-cyber-suit. Now Jim must make it to Princess-What\'s-Her-Name by staying clear of Psy-Crow, the intergalactic bounty hunter, until the final battle with Queen Slug-for-a-Butt.</p>', 'Eurocom', 'Playmates Interactive', 1995, 'action', 'a594667a18f06f9098b99a86a30146e41544094382.jpg', '2b067943628b0ba09c1a693423d926bf1544094382.jpg', 'ntonyyy', '2018-12-06 11:06:22', '5884bd455a5d481d085eace70054ee781544094382.mp3', 'New Junk City'),
(16, 'Halley Wars', 'Battle to the death with the legions of evil Lord Halley. The nations of the world have united to create the ultimate fighting machine in an attempt to stop the conquering invader. Use your supreme skills as a star-fighter pilot to blast back the alien destroyers, comets and missiles. Leave no survivors, for anything that gets past you slams into the Earth!', 'ITL', 'SEGA', 1991, 'shoot them  up', 'halley.jpg', 'https://gamefaqs.akamaized.net/screens/d/1/5/gfs_2685_2_1_mid.jpg', 'ntonyyy', '2018-11-25 23:00:00', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/halley-wars/05%20BGM%20%2302.mp3', 'Stage 1, 5 & 7 - Earth to the Moon, Comet Approach & Final Stand'),
(17, 'Land of Illusion starring Mickey Mouse', 'Mickey finds himself in a fairy tale land where an evil Phantom-in-the-Clouds has stolen a special gem which brought peace and prosperity to a tiny village. It\'s up to you to help him save the day - and earn a place in Minnie\'s heart!', 'SEGA', 'SEGA', 1993, 'platform', 'landofillusion.jpg', 'https://gamefaqs.akamaized.net/screens/9/e/b/gfs_68762_2_7_mid.jpg', 'ntonyyy', '2018-11-25 23:00:00', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/land-of-illusion-starring-mickey-mouse/03%20Phantom%27s%20Castle.mp3', 'Phantom\'s Castle'),
(54, 'Mortal Kombat II', 'NOTHING, NOTHING CAN PREPARE YOU! All the fierce kombatants of the #1 arcade smash gather for Mortal Kombat II, a battle to defeat the shape-shifting demon Shang Tsung and his ruthless master, Shao Kahn. Brutal special moves, Friendships, Babalities, hidden surprises, crushing combos and outrageous finishing moves - ALL yours to kommand. Let the Kombat kontinue...', 'Probe Entertainement Limited', 'Acclaim', 1994, 'vs fighting', 'mk2.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(55, 'Ninja Gaiden', 'The Dragon Ninja village has been massacred! The powerful Dragonsword has been stolen! You are Ryu Hayabusa, last of the Dragon Ninja, and you must find the Dragonsword before it can be used to unleash evil across the Earth!', 'Biox', 'SEGA', 1991, 'action', 'ninjagaiden.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(56, 'Out Run', 'Brace yourself for the most realistic racing experience yet. And to play, you\'ve got to have what it takes: NERVE, SKILL and BRAINS. NERVE - you\'re behind the wheel of a supertuned race car with one speed only: fast. SKILL - you\'re maneuvering a car that can nearly reach a simulated 270 KMH. BRAINS - because you\'re in control of your car\'s speed and handling at a dangerous pace, you have to use your head and not just your hands to survive. So get geared for the ride of your life and stay alert. The track may look terrific, but at these speeds anything can turn into a danger zone.', 'Sanritsu', 'Game Gear', 1991, 'racing', 'out run.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(57, 'Ristar', 'Ristar, the son of a legendary hero who\'s been captured, is the solar system\'s last hope against the evil space pirate Greedy. Ristar must travel to the 7 planets of his home system to restore peace to their once happy worlds and ultimately free his father. Ristar stretches his long elastic arms to grab enemies and head-butt them! His long limbs help him climb up walls or swing out of danger. Discover totally different worlds and new creatures on each planet! Battle strange beings who aren\'t always what they seem! Shoot through a variety of gameplay! Action, puzzle and strategy combine to challenge Ristar at every turn.', 'Biox', 'SEGA', 1995, 'platform', 'ristar.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(58, 'Samurai Shodown', 'Iza To! En Garde! Dude! Twelve of the mightiest samurai, ninja, knights, and warriors from Japan, France, the United States, and China lock swords in SAMURAI SHODOWN. With blades, bare knuckles, rage, and various Methods of Mayhem, fight your way to the final battle with Satan\'s Shogun. Use all powers at your disposal to get a head!', 'Takara', 'Takara', 1994, 'vs fighting', 'samuraishodown.jpg', '', 'ntonyy', '2018-11-30 13:26:33', '', ''),
(42, 'Alien Syndrome', '<p>The extra-terrestrials in this game are anything but friendly. They\'re slimy monsters that are holding space colonists captive aboard seven alien starships. This super action game challenges you to free the helpless hostages. Search each ship\'s deadly levels, using flamethrowers and laser cannons to vaporize alien scum. Look for maps to help you find your way. After you\'ve saved all the captives from one ship, you must destroy its powerful leader before you can move on to the next ship. Remember, to the aliens, you\'re slime. And they want you good... and dead!</p>', 'SIMS', 'SEGA', 1992, 'action', 'a071b8366ebb75a43435d69daf75a5651544091182.jpg', '229180994a9c0628c51da1eebb71ee9b1544091182.jpg', 'ntonyyy', '2018-12-06 10:13:02', 'e3ad13c0f5a7919cf6052e5f63ee36801544091182.mp3', 'Title Theme'),
(43, 'Battletoads', '<p>Okay \'toads! Let\'s get EVEN! When the evil Dark Queen kidnaps both your best buddy and the best looking girl this side of the Mazallion Star Cluster -what are you gonna do about it? Are you gonna cry? Hide? Call the Starcops? No way! Because you\'re a BATTLETOAD and BATTLETOADS don\'t cry, hide, or call for help. BATTLETOADS get real MAD-and then they get EVEN! So, strap on your Blaster, power-up the Toadster and get on downt o the Dark Queen\'s planet - but, watch out \'toad - this lady\'s bad, and she\'s got a whole mess of really nasty surprises lined up for you - like the Psyko Pigs, the Mutant Ratpack, Robo-Manus and the Saturn Toadtrap, to name but a few. You\'re gonna need all your fighting skills to defeat her - the Battletoad Butt, the Big Bad Boot and the Nuclear Knuckles. Hey, and don\'t forget to take along the Jet Turbo, the Space Board and the Speed Bike. Because you\'re gonna need \'em all, \'toad, if you\'re gonna rescue your friends and get the frog outta there with your green skin intact!</p>', 'Arc System Works', 'Tradewest', 1993, 'beat them all', '68c5aada4c99cecb6997633cb98ca4aa1544091623.jpg', '074cdcaa6a1b63dc76bb60a1275112f61544091623.jpg', 'ntonyyy', '2018-12-06 10:20:23', 'a49a92aa1b03d729a7b9132bac319f561544091623.mp3', 'Title Theme'),
(44, 'Chuck Rock', '<p>Once upon a rock, there was a primitive prince charming who was more evoled than the rest. His name: Chuck Rock. It\'s no wonder Ophelia fell for him like a two-ton boulder. They were living happily ever after until Gary Critter-one of Ophelia\'s many suitors-decided he had to have the lovely Ophelia for himself. So now it\'s time for you and Chuck to go Critter-hunting.</p>', 'Core Design', 'SEGA', 1992, 'platform', 'b92f9366b0169f6223dfa79e392b65c41544092679.jpg', '84d55fec3b02365696e1af04d6c2feda1544092679.jpg', 'ntonyyy', '2018-12-06 10:37:59', 'ddcd10ab4716720a9257dc8eb5dcf7ce1544092679.mp3', 'Title Theme'),
(45, 'Columns', '<p>Drift back in time to ancient Phoenicia and challenge yourself with Columns, an addictive game played by Middle Eastern merchants centuries ago. In this mesmerizing pastime, tinker with your riches to align glittering jewels across, down, or diagonally.</p>', 'SEGA', 'SEGA', 1990, 'puzzle', 'a0db85df2f48ad153eb7bb6b9eaad3721544092798.jpg', '4f64024cf910be480bbf7837072708461544092798.jpg', 'ntonyyy', '2018-12-06 10:39:58', '71be9d7387cb8478e7cc2df3f7bcc4781544092798.mp3', 'Gameplay Theme A'),
(46, 'Desert Speedtrap starring Road Runner', '<p>Blast off through the desert with Road Runner in this zany \'catch-me-if-you-can\' hyperspeed bird-seed adventure! But Wile E. Coyote is up to his old tricks. He wants Road Runner for dinner and he\'ll stop at nothing to succeed. - 12 stages of caves, sand, and ice. PLUS hard-to-find tunnels and secret rooms packed with bonus goodies. -\"Beep, Beep!\" It\'s a race against the clock. A fast food frenzy with piles of bird seed set along the desert road. - ZOO-OOM! Road Runner launches on springs to collect sky high power-ups. Watch out for hungry vultures, spiky cactus and booby-traps set by Wile E. Coyote</p>', 'Probe Entertainement Limited', 'SEGA', 1994, 'platform', 'd620d455085fdc984103247aed9cf8ba1544093335.jpg', '934159d12db417f983503178a6a732041544093335.jpg', 'ntonyyy', '2018-12-06 10:48:55', 'fa2a7e9debae7a1ac3afe1f5b3f214391544093335.mp3', 'Title Theme'),
(47, 'Desert Strike: Return to the Gulf', '<p>The Scuds are back! With a fiery blast from your Hellfire missiles you must annihilate a ruthless tyrant\'s military arsenal. Smoke his private yacht and tear into his air force as you challenge the Madman\'s forces in a series of surgical strikes. Rip through lots of fiery missions. Force is highly recommended.</p>', 'Electronic Arts', 'Domark', 1993, 'shoot\'em up', 'b1fb18f218d56a1269913b7b596c5b891544093560.jpg', 'aa599811b141b698e4bd51a66d9fbb731544093560.jpg', 'ntonyyy', '2018-12-06 10:52:40', '21dd134357c14c0d571508a1d67d21181544093560.mp3', 'Main Theme'),
(48, 'Fantasy Zone Gear', 'Take command of the spaceship Opa-Opa and blast your way through various fantastical levels as you try to take out all the enemy bases in each stage. Once you\'ve destroyed the bases, you\'ll have to beat the stage boss in order to move on to the next level. By using your guns and bombs wisely, you\'ll be able to take down your enemies and explore each of the crazy environments in this side-scroller. You can also buy upgraded weapons for your ship by accessing the shop.', 'Sanritsu', 'SEGA', 1991, 'shoot\'em up', 'fantasyzone.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(49, 'Global Gladiators', 'The bubble-blowing, goo-shooting, high-fivin\' Mick and Mack are unleashed into Sega action in their new global adventure, THE GLOBAL GLADIATORS! Vividly dramatic landscape and scenery fill every world as Mick and Mack spring, dash and blast through more than 1,250 frames of character animation - over ten times more than ever seen before! From skidding through perilous peaks in a world of ice, to dodging the infamous Red Snappy Piranha in the deep, dark Mystical Forest, Mick and Mack take players through four worlds and 12 levels of slime-busting fun! Add Mick and Mack\'s exclusive high-tech Goo Shooters and you\'ve got a Global Patrol ready to take on the world!', 'Virgin Games', 'Virgin Games', 1993, 'platform', 'globalgladiators.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(50, 'Gunstar Heroes', 'The Gunstar 9 planet was peaceful for many years until the vicious dictator Colonel Red kidnapped the Gunstar twins\' older brother and used mind control to make him his slave. Now, face many different enemies and bosses in Gunstar Heroes, as you battle to stop the dictator from unleashing \"Golden Silver the Destructor\" with apocalyptic consequences!', 'M2', 'SEGA', 1995, 'run & gun', 'gunstarheroes.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(51, 'The Jungle Book', 'Get down to the bare necessities of life... and escort Mowgli through the jungle to the safety of the human village. Fight the boggle-eyed snake, Kaa, and defeat Shere Khan the hungry tiger in this exciting adventure based on Disney\'s classic! It\'ll drive you ape crazy!', 'Syrox Developments', 'Virgin Games', 1993, 'platform', 'junglebook.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(52, 'The Lucky Dime Caper starring Donald Duck', 'Sorceress Magica De Spell and her rotten ravens have kidnapped Huey, Dewey and Louie! Worse yet, she\'s snatched Uncle Scrooge\'s Lucky Dime! Join Donald Duck in his quest to prove that Magica is no match for him.', 'Disney Interactive Studios', 'SEGA', 1991, 'platform', 'luckydimecaper.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(53, 'Mortal Kombat', 'PREPARE YOURSELF! The #1 arcade hit is here: from Sub-Zero, Rayden and the rest of the Kombat Warriors to the grueling endurance and intense mirror matches! Execute bone-shattering combos and awesome finishing moves! Defeat the half-human dragon Goro, and destroy the shape-changing Shang Tsung to become the Supreme Mortal Kombat Warrior!', 'Williams', 'Arena', 1993, 'vs fighting', 'mk.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(35, 'Streets of Rage', 'Axel and Blaze - ex-cops, the solution to punk pollution. The city\'s a war zone, and they\'re going out two at a time to give the gangs a kick in the guts. This is the ultimate in street combat. These city fighters are martial arts maniacs with a battery of individually controllable attacks - including jabs, head butts, and overhead kicks. They\'re up against a mob of Kung-Fu creeps and axe-hurling fiends. On the streets it\'s only two of them against hordes of attacking scum. Slam into pipe-wielding weirdos and bash \'em with their own metal. Throw an uppercut or an elbow smash - these goons keep comin\'!', 'Biox', 'SEGA', 1992, 'beat them all', 'sr.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(36, 'Streets of Rage II', 'Original rumblers Axel and Blaze slam the asphalt with bigger, better, totally devastating attacks! Skull-crushing ex-wrestler Max Thunder joins up with earth-shattering body slams and spinning fist attacks. New thrasher Skate slices punks with high speed in-line skate attacks and spinning jump kicks. Go maniac with jaw-shattering, bone-busting punches, head-cracking jump kicks and secret weapons. Gangs of dirt bikers dive into you from every side. Smash \'em with a pipe as they speed by.', 'Biox', 'SEGA', 1993, 'beat them all', 'sor2.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(37, 'Space Harrier', 'Laser blast and dodge your way through a frantic fantasy land swarming with unbelievable monsters and mutoids constantly coming at you. Accelerate through this arcade classic and answer the distress call... or pay the ultimate penalty!', 'SEGA', 'SEGA', 1991, 'shoot\'em up', 'spaceharrier.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(38, 'Tails Adventure', 'Tails is about to embark on his very own adventure. Walking through the forest he finds a small part of a very large machine, what is it? Now the excitement begins. Help Tails gather all the parts, defeating his enemies on the way and find the answer to the riddle...', 'Aspect', 'SEGA', 1995, 'platform', 'tailsadv.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(39, 'Tengen World Cup Soccer', 'Get Your Kicks On The Go!\r\n\r\n24 countries have shown up to claim the Tengen World Cup. But only one will go home a winner...\r\n\r\nStrap on your cleats and challenge the world for the ultimate soccer prize! Show your true colors and rip one past a gutsy Brazilian goalie. Dive on a Peruvian cannonball and save the day. Link up with a buddy and go head-to-head for ownership of the \"T\" Cup.\r\n\r\nItaly, France, U.S., Mexico... Choose your team from 24 of the most recognized soccer powers in the world.\r\n\r\nGoal kicks, shuffle passes, penalty kicks, defensive slides...do it all in a four-team elimination race for The Cup.\r\n\r\nYou\'ll get a kick out of the hottest graphics and action ever on the Game Gear.', 'SIMS', 'Tengen', 1993, 'sports', 'tengen.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(40, 'Wimbledon Tennis', 'Control one of the world\'s top players, or enter yourself in the Tour and test your skill. Featuring fast, heart-stopping action from beginning to end! Overhead smashes, blazing serves, passing shots, a practice mode and four prestigious tournaments - this game\'s got it all!', 'SIMs', 'SEGA', 1992, '', 'wimbledon.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(41, 'Wonder Boy III The Dragon\'s Trap', 'A Dragon\'s Curse can be hazardous to your humanity! Join Wonder Boy on his quest to end his curse and regain his human form.', 'West One', 'SEGA', 1992, 'adventure', 'wonderboy3.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(25, 'Fatal Fury Special', 'The GRANDMOTHER of all battles! 15 of the FATAL FURY series\' top stars gather in the match of the millenium! Use the resurrected Geese Howard and Wolfgang Krauser in a dazzling 3D arena! All you have ever wanted in a fighting game is here in FATAL FURY SPECIAL!', 'Gaibrain', 'Takara', 1994, 'vs fighting', 'fatalfuryspecial.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(26, 'James Pond II Codename Robocod', 'Dr. Maybe\'s dangerously fishy plans for world domination continue. In a slimy effort to sabotage the world\'s largest toy factory, he has planted penguin-bombs in toy factories inside the North Pole. James Pond bubbles to the rescue as RoboCod in another massive oceanic adventure! Featuring a massive play area - over 2,500 colorful screens of action-packed gameplay; 8 enormous levels, each with lots of sections; Discover many bonus rooms; Amazing gravity impetus super-scroll!', 'Millenium', 'US Gold', 1993, 'platform', 'jamespond2.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(27, 'Krusty\'s Fun House', 'Hey, kids! Give a hoot! Help out your old pal Krusty the Clown! My official Krusty\'s Fun House is infested with rats! I\'ve got my loyal cadets, Bart and Homer Simpson, Sideshow Mel, and Corporal Punishment to guard the rat traps, but I need you to lead the filthy rodents into those traps! Then we blow \'em up! We incinerate \'em! We laser-blast \'em! We electrocute \'em! We Krusterize the little stinkers! Hoo boy! Did I mention the snakes, aliens and flying pigs? Well, watch out for those riffraff! If you can\'t Krusterize \'em, at least avoid \'em... they\'re worse than the #@!*%! rats! Making Krusty\'s Fun House vermin-free is not a pretty task, kiddy cadets - but someone\'s gotta do it!', 'Audiogenic Ltd', 'Flying Edge', 1993, 'puzzle', 'krusty.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(28, 'Mega Man', 'Blast-Off With Mega Man For The Thrill Of Your Life!\r\n\r\nMega Man must stop Dr. Wily from his no good sinister plan to destroy civilization. But hold onto those mega-boosters, this job is not going to be easy. Dr.Willy, who is hiding out in his super fortress, has an array of mega-obstacles just waiting for Mega Man. But with your help and a ton of mega-weapons,\r\nyou have a 50/50 chance of stopping Dr. Wily. So don\'t whimp-out...get ready for battle in this resurrected saga of the greatest adventures of Mega Man.', 'Freestyle', 'US Gold', 1995, 'action', 'megaman.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(29, 'Micro Machines', 'Hit the gas and race on 16 outrageous, high-speed tracks in 8 different worlds. It\'s totally unique racing action in an oversized world where anything (and everything!) can happen.', 'Codemasters', 'Codemasters', 1993, 'racing', 'micromachines.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(30, 'Robocop vs the Terminator', 'In the crumbling ruins of a world under siege, man-machine meets machine-man as legendary cyborgs clash to decide the fate of the Earth. As Robocop, you must travel across time into a bloody future ruled by the mechanical forces of Skynet. You\'ll face attack from every angle, every moment. An unwavering army of Terminators, robotic dogs, spiders, Endoskeletons and a relentless arsenal of automated weapons await you in this veritable hell on earth. To destroy this enemy, free its hostages and finally pierce the dark heart of a killer computer. It will take something more powerful than plasma rifles and laser guns: the human mind that still burns within you.', 'NMS Software', 'Virgin Games', 1993, 'action', 'robovsterm.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(31, 'Slider', 'As Slider, you must stop the poisoning of your homeland, Rozen, by the diabolical Scum lords!', 'Loriciels', 'SEGA', 1991, 'puzzle', 'slider.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(32, 'Sonic the Hedgehog 2', 'Super Speed! Sonic\'s back and better than ever. He\'s a blur in blue! A blaze of action! With his new Super Spin Dash. And a new, fabulous friend, \"Tails\" the Fox. You won\'t believe it \'til you see it. And when you play, you won\'t stop. Super Play! Defy gravity in hair-raising loop-de-loops. Grab Power Sneakers and race like lightning through the mazes. All at break-neck speed! Super Power! Sonic\'s attitude is can-do. The mad scientist Dr. Robotnik is planning a world takeover. Sonic gets tough in the fight to save his friends and squash Robotnik for good!', 'Aspect', 'SEGA', 1992, 'platform', 'sonic2.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(33, 'Sonic the Hedgehog Chaos', 'Dr. Robotnik\'s stolen the red Chaos Emerald, and it\'s up to Sonic The Hedgehog to get it back! As Sonic or \"Tails\" the two-tailed fox, you\'ll zip through the Zones, using your quick moves and quicker thinking to collect rings and evade Robotnik\'s latest batch of badniks!', 'Aspect', 'SEGA', 1993, 'platform', 'sonicchaos.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(34, 'Sonic the Hedgehog Triple Trouble', 'Sonic and Tails are back with three times the fun and three times the trouble! Dr. Robotnik is building the ultimate super-weapon with the help of Knuckles, but you can stop him by getting the Chaos Emeralds first. Rip across snow and water on Sonic\'s new jet skateboard or zip underwater in Tails\' \"Sea Fox\". But look out - Nack the Weasel is after the Emeralds, too!', 'Aspect', 'SEGA', 1994, 'platform', 'sonictripletrouble.jpg', '', 'ntonyyy', '2018-11-30 13:26:33', '', ''),
(19, 'Aerial Assault', '<p>It\'s the 21st century and N.A.C., a feared terrorist group of the galaxy, threatens to destroy Earth. They\'ve developed the super weapon \"EL\" that will blast away Earth\'s ozone layer. And they\'ve threatened to use it! As the world\'s top jet fighter pilot, you\'re in command of the of the ultimate in combat aircraft - the \"Freedom Fighter.\" Armed with the latest in new high-tech weaponry, you and your jet are Earth\'s only chance against the merciless N.A.C.</p>', 'SIMS', 'SEGA', 1992, 'shoot them up', '440476e7fd4f01bf12f6973852b12b671543963201.jpg', '2accf76b1d97e62f53436160f0a8cc631543963201.png', 'ntonyyy', '2019-01-09 18:51:36', '5f674cafeaeaf294ff9d6a4725be8d651543963201.mp3', 'EL'),
(20, 'Aladdin  ', '<p>Hang on to your carpet for ACTION and FUN! Aladdin slashes his shining scimitar to fight through Agrabah, escape the Sultan\'s dungeon, survive the fiery Cave of Wonders, snatch the Genie\'s Lamp and save Princess Jasmine from the evil Jafar! Aladdin battles thieves and desert warriors, and barely dodges danger on his high-speed carpet. Palace Guards drop their drawers and camels spit dirt wads. Aladdin ping-pongs like a pinball inside the Genie\'s Lamp!</p>', 'SIMS  ', 'SEGA  ', 1993, 'platform  ', '650c33ea72fdc4d236e21d5f07f007541544091018.jpg', '904909db952d623fed6080c311b1297b1544091018.jpg', 'ntonyyy  ', '2019-01-25 10:33:53', '215ecfee04e50f81fced8ddc156226ee1544091018.mp3', 'One Jump Ahead  '),
(21, 'Baku Baku', '<p>You\'re the zookeeper in a crazy kingdom. But you\'d better watch out - once you dive into the Baku Baku den, there\'s no turning back... To win, match each animal with its favorite food. Challenge computer characters or go head-to-head in 2-player mode. Beautiful 3D graphics and stunning colors bring puzzling to the next level. Variable game speed lets you go slow-mo or full throttle. Better be clever - surprises await true Baku masters...</p>', 'Minato Giken', 'SEGA', 1996, 'puzzle', 'e3d7da2e8a1dc5533bc05e7417223b791544091422.jpg', '1959bb6e599bc19e3806cc41181b89f41544091422.jpg', 'ntonyyy', '2018-12-06 10:17:02', '04d2c2efd3972bd8456b0adf986b2de91544091422.mp3', 'Frantic Action'),
(22, 'Bust-a-Move', '<p>Which will burst first: your concentration or the level you\'re working on? It takes more than just swinging the bubble-turret and taking aim on the falling ceiling; tactical planning and mental dexterity are the only way to string together three or more bubbles and 100 wins to make it through all the bubble and ego-bursting rounds of Bust-A-Move!</p>', 'Santos', 'Taito', 1996, 'puzzle', '2e98ab3a2fb7ef6cf91ea7e4638e745c1544091751.jpg', '3746a893a0f96da17b9c672d23a0d8f01544091751.jpg', 'ntonyyy', '2018-12-06 10:22:31', '9d6895fb7a21bb5d487e82e9e7bf5f6f1544091751.mp3', 'Let\'s go to Pao Pao Island'),
(23, 'Defenders of Oasis', '<p>As the Prince, you must defend the world of Oasis from the dark forces in this challenging real-time role-playing game!</p>', 'SEGA', 'SEGA', 1992, 'role playing game', '5fdae882637e74948d87bbcaec9444eb1544093105.jpg', 'f341d3e7dd26aede2d73019f6c0741e81544093105.jpg', 'ntonyyy', '2018-12-06 10:45:05', '53d03667852f73d3abc0af407bbaec441544093105.mp3', 'Boss Battle'),
(24, 'Dragon Crystal ', '<p>You\'re caught in a fantastic world of unearthly beauty and deadly demons. You\'ll pass through thirty worlds in search of the Magic Goblet. There\'s no way out of this musical nightmare...until you find it.</p>', 'SEGA ', 'SEGA ', 1990, 'role playing game ', 'ecda6480514d099be6b88fb5687e0f9b1548759227.jpg', '3fb2db6cccf4a23383383394b28b2b311548759227.jpg', 'ntonyyy ', '2019-01-29 10:49:10', 'b2a74ce5aed8e34ba0d92c02b254da721548759227.mp3', ' Levels 1 to 10'),
(18, 'Mighty Morphin Power Rangers', 'It\'s Morphin Time! Five ordinary teens morph into the Power Rangers to foil the plans of the Evil Empress Rita Repulsa and save planet Earth. Choose your favorite Power Ranger color - Red, Yellow, Blue, Pink or Black! Battle huge, fierce and spectacular enemies! Even the Green Ranger and the fearsome Dragonzord!', 'SIMS', 'SEGA', 1994, 'action', 'powerrangers.jpg', 'https://gamefaqs.akamaized.net/screens/a/e/a/gfs_39193_2_8.jpg', 'ntonyyy', '2018-11-25 23:00:00', 'http://66.90.93.122/soundfiles/sega-game-gear-sgc/mighty-morphin-power-rangers/01%20BGM%20%2301.mp3', 'Introduction'),
(66, 'Puyo Puyo', '<p>Puyo Puyo is a Puzzle game, developed by Compile and published by Sega, which was released in Japan in 1993.</p>', 'Compile', 'SEGA', 1993, 'puzzle', 'ec67b008cb6be9a8c5580844b541bcd91544096964.jpg', '5b2aac47ddab31a5fabaaf196d011cd51544096964.jpg', 'ntonyyy', '2018-12-06 11:49:24', 'cc6b112dc7f289d0f664113ae9ecade91544096964.mp3', 'Theme of Puyo Puyo'),
(59, 'Shining Force the Sword of Hajya', 'The peaceful kingdom of Cypress has suddenly been disrupted by the corrupt ambition of the evil King Iom. Terror rampages across the land. The Castle of Cypress is invaded and the magical Sword of Hajya is taken! It will take strength, courage, agility and your keen sense of strategy to defy this ominous power.', 'Camelot Software Planning', 'SEGA', 1993, 'strategy', 'shiningforcegaiden2.jpg', '', 'ntonyyy', '2018-11-30 13:30:29', '', ''),
(60, 'The Smurfs', 'Gargamel has already captured three Smurfs. Smurf to their rescue! Smurf down the mountains riding on a sledge, explore the labyrinths of the mine, travel on the back of a stork... but beware of nasty enemies such as the Buzz flies, the Angry Smurfs, the Howlibird, Azrael and... Gargamel!', 'Bit Managers', 'Infogrames', 1995, 'platform', 'smurfs.jpg', '', 'ntonyyy', '2018-11-30 13:30:29', '', ''),
(61, 'The Terminator', 'Kyle Reese, a lone warrior from the future, returns to the past to protect the one woman who holds the key to the survival of the human race. Together they must face not only everything Los Angeles has to throw at them but also the terrifying might of a cyborg known at the Terminator... who will stop at nothing to kill them both.', 'Probe Entertainement Limited', 'Virgin Games', 1992, 'action', 'term.jpg', '', 'ntonyyy', '2018-11-30 13:30:29', '', ''),
(62, 'Tintin au Tibet', 'Re-live the adventures of Tintin on the search for his friend Chang. What happened to Chang after the crash of the DC3 on the way to Kotmondu? Set off with Tintin to Tibet where all along your exciting journey you\'ll find vital items to aid your progress and interrogate the locals for helpful advice. You\'ll face many a danger as you examine the aeroplane wreck, climb on steep rock walls and meet the legendary Yeti.', 'Bit Managers', 'Infogrames', 1996, 'platform', 'tintin.jpg', '', 'ntonyyy', '2018-11-30 13:30:29', '', ''),
(63, 'Wolfchild', 'Using his father\'s scientific knowledge, Saul Morrow transforms himself into the powerful WOLFCHILD and seeks revenge on the evil Chimera organization who have murdered his family and kidnapped his father. Guide Saul in his quest to rescue his father from the clutches of the corrupt Chimera corporation. Change his form to that of a powerful psychic werewolf as you fight your way through 5 levels of action-packed adventure, featuring over 400 screens of exciting and addictive gameplay!', 'Core Design', 'Virgin Games', 1993, 'action', 'Wolfchild.jpg', '', 'ntonyyy', '2018-11-30 13:30:29', '', ''),
(64, 'NBA Jam', 'The popular granddaddy of arcade-style basketball is back. NBA Jam brings the supercharged, \"in-your-face\" highlights of NBA play to life with over-the-top, thrilling three-on-three basketball. Perform monster dunks and alley-oops and shoot from valuable hotspots to catch \"on-fire\" and obliterate the competition. You can choose from all 29 current NBA teams, players, and arenas and even outdoor playground courts like Rucker Park and LA\'s Venice Beach. With no fouls to slow down the game, be as rough and flashy as you can be.', 'Iguana Entertainement', 'Arena', 1994, 'sports', 'nbajam.jpg', '', 'ntonyyy', '2018-11-30 13:30:29', '', ''),
(65, 'Olympic Gold', '<p>Experience for yourself the thrill and excitement of competing in seven spectacular Olympic track, field and pool events. Olympic Gold, the challenge - to win you\'ll need all the strength, skill and determination you can muster!</p>\r\n<p style=\"text-align: center;\"><img src=\"https://gamefaqs.akamaized.net/screens/a/3/5/gfs_89125_2_4.jpg\" /></p>', 'US Gold', 'US Gold', 1992, 'sports', '0c353eb5b3a1d1d501f77e7b36ec38161543617950.jpg', 'screenshot.png', 'ntonyyy', '2018-11-30 22:45:50', '752a404450b5f3db3701f677903fb4791543617950.mp3', 'Menu Theme'),
(67, 'Woody Pop', '<p>The Mad Machine has shut down the Enchanted Mansion toy factory. Massive barricades have been set up, blocking off all contact with the outside world. The only thing the crazed machien didn\'t count on was resistance from a courageous wooden toy--Woody Pop! Join Woody as he clashes with mechanized forces and nearly impossible barriers.</p>', 'SEGA', 'SEGA', 1991, 'casse brique', '2a638427fa2308feaa60aadb609782241543849007.jpg', '597783cb1ca22402666c860fb7f36e501543849007.jpg', 'ntonyyy', '2018-12-03 14:56:47', '50e0223a4c2c8055c86863baf1c3e95b1543849007.mp3', 'Title'),
(68, 'Super Monaco GP', '<p>Fry up the track on long straightaways, or downshift into neck-wrenching hairpin curves. Super Monaco GP sends you screaming around the most demanding tracks on earth in the hottest racecar ever built, the Formula 1. Choose your car\'s transmission. Slide through a practice run with an automatic, battle rival drivers with a 4-speed, or grind gears to victory piloting a 7-speed machine. Burn rubber with the best drivers around in a piston-pounding test of speed, road savvy, and endurance!</p>', 'SEGA', 'SEGA', 1991, 'Title Theme', '150db48e7ae3b51d2557d3d4c5e066da1543962389.jpg', '70a41326614241fc33d1db6447a8801a1543962389.jpg', 'ntonyyy', '2018-12-04 22:29:56', '564aff471f7e63bdeb475de6afebcd871543962389.mp3', 'Title Theme'),
(69, 'Super Smash TV', '<p>Congratulations! You\'re the next lucky contestant on the game show with the ultimate in prizes... YOUR LIFE! Pick six futuristic weapons and defeat hordes of cyborg mutants, power orbs, assault tanks and the 30-ton mutoid man!</p>', 'Probe Entertainement Limited', 'Flying Edge', 1994, 'action', '917d69509f21e17977a95e7dc5b652581543949766.jpg', 'e4cdbcbe58c258c14d9688368fd0952c1543949766.jpg', 'ntonyyy', '2018-12-04 18:56:06', 'f89733f941a8c72db32549b5a4aaf1b41543949766.mp3', 'Title Theme'),
(70, 'Jurassic Park', '<p>Plunge into a heart-wrenching race for survival! On a tropical island, a violent hurricane rips through the dinosaur preserve, trapping the tourists and freeing the most terrifying animals in prehistory! Two bigger-than-life ways to play: Be a dinosaur! As a Raptor, rampage across the island battling other beasts and eluding the traps and weapons of your human enemies. As Grant, the paleontologist, arm yourself with tranquilizer guns, and sleeping-gas grenades. Dodge the slashing jaws of the Tyrannosaurus Rex and the paralyzing spit of the Dilophosaurs! 16 mammoth megs of nerve-shredding action!The computer in Jurassic Park has broken down and the animals have all escaped! You\'re the only thing that stands between the dinosaurs and the people on the island. Do you have what it takes to save the day?</p>', 'SEGA', 'SEGA', 1993, 'action', '8d70a4a828285be8a64e79e670c902241543954414.jpg', '1733b74d609338785e0045069739a1151543954414.png', 'ntonyyy', '2018-12-04 20:13:34', '893ff73dce0e356030b1b69bb2d882d11543954414.mp3', 'Triceratops'),
(71, 'Hook', '<p>Your blood is pumping and a chill races down your spine! You\'ve finally come face-to-face with the most infamous pirate of them all, Captain Hook, the fiend who\'s kidnapped your children and sworn never to let them go. As Peter Pan, this is the fight of your life. Everything that came before - your duel with Rufio, your battles against the pirates, even your soaring flights high above Neverland - are nothing compared to this moment. Lots of fun levels of incredible excitement. Multiple destinations: forests, caves, caverns, towns, lagoons, icy regions, and the Nevertree. Magical items that will give you strength and special powers: apples, leaves, and pixie dust.</p>', 'Spidersoft', 'Sony Imagesoft', 1992, 'platform', '136ee354f25e5be69f5874eb0ba0ce001543955210.jpg', 'e4b4135dcb3f6cc42a3c27a559d5b7a41543955210.png', 'ntonyyy', '2018-12-04 22:18:14', 'f9cfd6cb68cf919332f9b539a82624e41543955210.mp3', 'SEGA'),
(209, 'Super Off Road', '<p>Super Off-Road is the ultimate off-road racing event. Four tough trucks speed around rough and ready tracks packed with pitfalls, power-boosters and prizes. No one knows the meaning of sportsmanship here. Have you got the skill and determination to come out on top?</p>', 'Graftgold', 'Virgin Games', 1992, 'racing', '8d86b6e9d2345b10cf6251f9e91be9291543963674.jpg', '5a06fc50574feadb5374bc99ffd373f71543963674.jpg', 'ntonyyy', '2018-12-04 22:47:54', '97e07467df9b686f011aae4665a42c4f1543963674.mp3', 'Title Theme'),
(210, 'Tempo Jr', '<p>Music can be fun! Tempo, the hip-hoppin\' grasshopper. lives in the musical world of planet Rhythmia. It\'s up to Tempo to save the rhythm and give King Dirge the blues!</p>\r\n<p>Tempo boogies, spins, snaps his fingers and slings notes to zap King Dirges tune-swiping ants.</p>\r\n<p>Music is the key! Collect CDs to charge up Tempo\'s energy. Learn about notes in the bonus round!</p>\r\n<p>5 rockin\' stages, each with its own rollin\' beat!</p>', 'SIMS', 'SEGA', 1995, 'platform', '397974dce4355fdddb05368d90f11fee1543964310.jpg', 'bf158ed4e223f7dcc75537d25f18169e1543964310.jpg', 'ntonyyy', '2018-12-04 22:58:30', '31e7fdabe763461fdd8fe61c0aff782e1543964310.mp3', 'BGM #7'),
(211, 'Devilish', '<p>Anyone can break through a couple of brick walls, right? Well, breaking through barriers is only a small part of this mission. Tons of beasts, bodies, blockades, and other bad seed await you as you travel through a series of eight daring and challenging stages.<br />Dodge through graveyards and waterfalls, slide through a world of ice, and with a little luck, you\'ll reach the Evil Temple, where you\'ll come face to face with your most evil nemesis, Gamma.<br />But Gamma doesn\'t even expect you to make it to the end, because he has placed plenty of his best beasts and boobie-traps on each level to aid in your demise. And at the end of each level, you must battle one of Gamma\'s most devoted creatures of darkness before you can move on to the next challenge.<br />But don\'t worry. We\'ve equipped you with our specialized dual-paddle system. And there are four different paddle formations to give you maximum control of the Power Orb.</p>', 'Opera House', 'Sage\'s Creation', 1991, 'casse brique', 'cover.png', 'screenshot.png', 'ntonyyy', '2018-12-05 17:19:03', 'track.mp3', 'SEGA'),
(221, 'Taz-Mania', '<p>Watch TAZ\'s dust! That spinning superstar with the short fuse and gigantic appetite! TAZ whirls across Tasmania, hunting for the lost giant seabird egg to make the world\'s largest omelet! TAZ gobbles up everything! Snacks like chilli peppers really burn up his enemies. The hungrier he is, the wilder he gets. Explosive TAZ blasts through multiple levels of high-energy adventure. He rides waterspouts, skids on ice and whizzes through mine shafts in a runaway cart! Villains from the Warner Bros. hit TV series join the mischief, including the Bush Rats, Francis X, Bushlad, Bull Gator and others !</p>', 'NuFX', 'SEGA', 1994, 'platform', 'b72c9e0c966b03d31655fbc993fc9fb21548805326.jpg', '704b27084030f0e97ce3ce3e5953e9e51548805326.jpg', 'ntonyyy', '2019-01-29 23:47:13', 'b3be0671af1c2135e0faa0986301bf3f1548805326.mp3', 'The Badlands');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(255) NOT NULL,
  `pass` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `register_date` date NOT NULL,
  PRIMARY KEY (`id`)
) ;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `pseudo`, `pass`, `email`, `register_date`) VALUES
(8, 'gg', 'f5678f1aa83c871e4d0218f20af62aa11dcbae74', 'gg@gg.com', '2019-01-22'),
(7, 'deletetest', 'a0ff094025db6249d90f911e531633bdaea45616', 'deletetest@blabla.com', '2019-01-17'),
(6, 'TOTO', '17e66b77b21bf57f6ea4efc179b416f10e9bdc6b', 'TOTO@toto.com', '2019-01-15');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
